server:
  port: 8083
spring:
  application:
    name: order
  datasource:
    url: jdbc:postgresql://localhost:5432/ecom_order
    username: ecommerce
    password: ecommerce
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
